plugins {
    id 'java'
    id 'java-library'
    id 'application'
}

group 'com.petrokhovrashchuk.petprojects'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jsoup:jsoup:1.21.1")
    implementation("org.projectlombok:lombok:1.18.38")
    implementation("com.google.dagger:dagger:2.57.1")
    annotationProcessor("org.projectlombok:lombok:1.18.38")
    annotationProcessor("com.google.dagger:dagger-compiler:2.57.1")
    testImplementation("org.testng:testng:7.11.0")
    testImplementation("org.assertj:assertj-core:3.27.4")
    testImplementation("org.mockito:mockito-core:5.19.0")
    testImplementation("org.mockito:mockito-testng:0.5.2")
    testImplementation("com.google.jimfs:jimfs:1.3.1")
}

application {
    mainClass = 'com.petrokhovrashchuk.petprojects.HtmlToInputFormatTransformer'
    applicationName = 'html-to-input-format-transformer'
}

test {
    useTestNG()
}